"""
Enhanced PDF Report Generator
Professional-grade portfolio reports with AI insights, charts, branding,
and comprehensive formatting
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, 
    Spacer, PageBreak, Image, KeepTogether
)
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF
from datetime import datetime
from typing import Dict, List, Optional, Any, Tuple
import io
import os
import logging
import tempfile

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ========================================
# COLOR SCHEME
# ========================================

class ColorScheme:
    """Professional color scheme for reports"""
    PRIMARY = colors.HexColor('#1e40af')  # Blue
    SECONDARY = colors.HexColor('#7c3aed')  # Purple
    SUCCESS = colors.HexColor('#059669')  # Green
    WARNING = colors.HexColor('#d97706')  # Orange
    DANGER = colors.HexColor('#dc2626')  # Red
    
    BACKGROUND_LIGHT = colors.HexColor('#f3f4f6')
    BACKGROUND_LIGHTER = colors.HexColor('#f9fafb')
    
    TEXT_PRIMARY = colors.HexColor('#1f2937')
    TEXT_SECONDARY = colors.HexColor('#6b7280')
    TEXT_LIGHT = colors.HexColor('#9ca3af')
    
    BORDER = colors.HexColor('#d1d5db')
    BORDER_LIGHT = colors.HexColor('#e5e7eb')
    
    AI_BACKGROUND = colors.HexColor('#faf5ff')
    AI_BORDER = colors.HexColor('#c084fc')
    AI_TEXT = colors.HexColor('#6b21a8')


# ========================================
# NUMBERED CANVAS (FOR PAGE NUMBERS)
# ========================================

class NumberedCanvas(canvas.Canvas):
    """Canvas with page numbers and footer"""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []
    
    def showPage(self):
        """Show page and save for later processing"""
        self.pages.append(dict(self.__dict__))
        self._startPage()
    
    def save(self):
        """Add page numbers and save"""
        page_count = len(self.pages)
        
        for page_num, page_dict in enumerate(self.pages, 1):
            self.__dict__.update(page_dict)
            self.draw_page_number(page_num, page_count)
            canvas.Canvas.showPage(self)
        
        canvas.Canvas.save(self)
    
    def draw_page_number(self, page_num: int, page_count: int):
        """Draw page number and footer"""
        # Page number
        self.setFont('Helvetica', 9)
        self.setFillColor(ColorScheme.TEXT_SECONDARY)
        
        page_text = f"Page {page_num} of {page_count}"
        self.drawRightString(
            7.5 * inch,
            0.5 * inch,
            page_text
        )
        
        # Footer text
        footer_text = f"Generated by VisionWealth | {datetime.now().strftime('%B %d, %Y')}"
        self.drawString(
            1 * inch,
            0.5 * inch,
            footer_text
        )


# ========================================
# ENHANCED PDF GENERATOR
# ========================================

class EnhancedPDFReportGenerator:
    """
    Generate professional portfolio reports with AI insights.
    
    Features:
    - Custom styling and branding
    - AI-powered insights
    - Interactive charts
    - Comprehensive analytics
    - Page numbering
    - Professional formatting
    """
    
    def __init__(self):
        """Initialize PDF generator with custom styles"""
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        logger.info("Enhanced PDF generator initialized")
    
    def _setup_custom_styles(self):
        """Define custom paragraph styles"""
        
        # Custom Title
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=28,
            textColor=ColorScheme.PRIMARY,
            spaceAfter=30,
            spaceBefore=10,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Section Header
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=ColorScheme.TEXT_PRIMARY,
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold',
            borderColor=ColorScheme.PRIMARY,
            borderWidth=0,
            borderPadding=5,
            leftIndent=0
        ))
        
        # Subsection Header
        self.styles.add(ParagraphStyle(
            name='SubsectionHeader',
            parent=self.styles['Heading3'],
            fontSize=13,
            textColor=ColorScheme.TEXT_PRIMARY,
            spaceAfter=8,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        # AI Insight Box
        self.styles.add(ParagraphStyle(
            name='AIInsight',
            parent=self.styles['BodyText'],
            fontSize=11,
            textColor=ColorScheme.AI_TEXT,
            leftIndent=20,
            rightIndent=20,
            spaceAfter=15,
            spaceBefore=10,
            borderColor=ColorScheme.AI_BORDER,
            borderWidth=1,
            borderPadding=12,
            backColor=ColorScheme.AI_BACKGROUND,
            leading=14
        ))
        
        # Emphasis Text
        self.styles.add(ParagraphStyle(
            name='Emphasis',
            parent=self.styles['BodyText'],
            fontSize=11,
            textColor=ColorScheme.TEXT_PRIMARY,
            fontName='Helvetica-Bold',
            spaceAfter=6
        ))
        
        # Small Text
        self.styles.add(ParagraphStyle(
            name='SmallText',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=ColorScheme.TEXT_SECONDARY,
            spaceAfter=4
        ))
        
        # Disclaimer
        self.styles.add(ParagraphStyle(
            name='Disclaimer',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=ColorScheme.TEXT_SECONDARY,
            alignment=TA_JUSTIFY,
            leftIndent=10,
            rightIndent=10,
            spaceAfter=10,
            leading=12
        ))
    
    def generate_report(
        self,
        portfolio_data: Dict,
        analytics: Dict,
        ai_insights: Optional[Dict] = None,
        output_path: Optional[str] = None,
        client_name: str = "Client"
    ) -> bytes:
        """
        Generate comprehensive PDF report.
        
        Args:
            portfolio_data: Portfolio holdings and metadata
            analytics: Risk metrics, allocation, performance
            ai_insights: AI-generated analysis (optional)
            output_path: Optional file path to save PDF
            client_name: Client name for personalization
        
        Returns:
            PDF as bytes
        """
        try:
            logger.info(f"Generating enhanced PDF report for: {client_name}")
            
            # Create buffer
            buffer = io.BytesIO()
            
            # Create PDF document with numbered canvas
            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=0.75*inch,
                leftMargin=0.75*inch,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch,
                title=f"Portfolio Report - {client_name}",
                author="VisionWealth"
            )
            
            # Build content
            story = []
            
            # Cover page
            story.extend(self._create_cover_page(portfolio_data, client_name))
            story.append(PageBreak())
            
            # Executive Summary
            story.extend(self._create_executive_summary(
                portfolio_data, analytics, ai_insights
            ))
            story.append(Spacer(1, 0.3*inch))
            
            # Key Metrics Dashboard
            story.extend(self._create_key_metrics(portfolio_data, analytics))
            story.append(Spacer(1, 0.3*inch))
            
            # Portfolio Overview
            story.extend(self._create_portfolio_overview(portfolio_data))
            story.append(PageBreak())
            
            # Holdings Detail
            story.extend(self._create_holdings_table(portfolio_data))
            story.append(PageBreak())
            
            # Risk Analysis
            story.extend(self._create_risk_analysis(analytics))
            story.append(Spacer(1, 0.3*inch))
            
            # Allocation Analysis
            story.extend(self._create_allocation_section(analytics))
            story.append(PageBreak())
            
            # Performance Analysis
            if analytics.get('performance'):
                story.extend(self._create_performance_section(analytics))
                story.append(Spacer(1, 0.3*inch))
            
            # AI Insights
            if ai_insights:
                story.extend(self._create_ai_insights_section(ai_insights))
                story.append(PageBreak())
            
            # Recommendations
            if ai_insights and ai_insights.get('recommendations'):
                story.extend(self._create_recommendations_section(ai_insights))
                story.append(Spacer(1, 0.3*inch))
            
            # Disclaimer
            story.extend(self._create_disclaimer())
            
            # Build PDF with numbered pages
            doc.build(story, canvasmaker=NumberedCanvas)
            
            # Get PDF bytes
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            # Optionally save to file
            if output_path:
                with open(output_path, 'wb') as f:
                    f.write(pdf_bytes)
                logger.info(f"PDF saved to: {output_path}")
            
            logger.info(f"PDF report generated successfully ({len(pdf_bytes)} bytes)")
            return pdf_bytes
        
        except Exception as e:
            logger.error(f"Error generating PDF report: {e}", exc_info=True)
            raise
    
    def _create_cover_page(self, portfolio_data: Dict, client_name: str) -> List:
        """Create professional cover page"""
        elements = []
        
        # Add spacing
        elements.append(Spacer(1, 1.5*inch))
        
        # Title
        title = Paragraph(
            "<b>Portfolio Analysis Report</b>",
            self.styles['CustomTitle']
        )
        elements.append(title)
        elements.append(Spacer(1, 0.5*inch))
        
        # Client name
        elements.append(Paragraph(
            f"<b>{client_name}</b>",
            ParagraphStyle(
                name='ClientName',
                parent=self.styles['Heading2'],
                fontSize=18,
                textColor=ColorScheme.TEXT_PRIMARY,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 0.3*inch))
        
        # Date
        date_str = datetime.now().strftime("%B %d, %Y")
        elements.append(Paragraph(
            f"<i>Generated on {date_str}</i>",
            ParagraphStyle(
                name='DateStyle',
                parent=self.styles['Normal'],
                fontSize=11,
                textColor=ColorScheme.TEXT_SECONDARY,
                alignment=TA_CENTER
            )
        ))
        elements.append(Spacer(1, 1*inch))
        
        # Key metrics box
        summary = portfolio_data.get('summary', {})
        total_value = summary.get('total_value', 0)
        num_holdings = summary.get('num_holdings', 0)
        total_return = summary.get('overall_return_pct', 0)
        
        metrics_data = [
            ['Total Portfolio Value', f"${total_value:,.2f}"],
            ['Number of Holdings', str(num_holdings)],
            ['Total Return', f"{total_return:,.2f}%"],
            ['Report Type', 'Comprehensive Analysis']
        ]
        
        metrics_table = Table(metrics_data, colWidths=[3*inch, 2.5*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), ColorScheme.BACKGROUND_LIGHT),
            ('TEXTCOLOR', (0, 0), (-1, -1), ColorScheme.TEXT_PRIMARY),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 15),
            ('RIGHTPADDING', (0, 0), (-1, -1), 15),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))
        
        elements.append(metrics_table)
        elements.append(Spacer(1, 1*inch))
        
        # Powered by
        elements.append(Paragraph(
            "<i>Powered by VisionWealth Portfolio Analytics</i>",
            ParagraphStyle(
                name='PoweredBy',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=ColorScheme.TEXT_LIGHT,
                alignment=TA_CENTER
            )
        ))
        
        return elements
    
    def _create_executive_summary(
        self,
        portfolio_data: Dict,
        analytics: Dict,
        ai_insights: Optional[Dict]
    ) -> List:
        """Create executive summary with AI insights"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Executive Summary</b>",
            self.styles['SectionHeader']
        ))
        
        if ai_insights and ai_insights.get('summary'):
            # AI-generated summary
            summary_text = ai_insights['summary']
            elements.append(Paragraph(
                summary_text,
                self.styles['AIInsight']
            ))
        else:
            # Fallback summary
            summary = portfolio_data.get('summary', {})
            total_value = summary.get('total_value', 0)
            num_holdings = summary.get('num_holdings', 0)
            total_return = summary.get('overall_return_pct', 0)
            
            summary_text = f"""
            This portfolio consists of <b>{num_holdings} holdings</b> with a total value of 
            <b>${total_value:,.2f}</b>. The portfolio has achieved a total return of 
            <b>{total_return:+.2f}%</b>. This comprehensive analysis includes risk metrics, 
            sector allocation breakdown, performance analytics, and strategic recommendations.
            """
            elements.append(Paragraph(summary_text, self.styles['BodyText']))
        
        # Portfolio health score
        if ai_insights and ai_insights.get('score'):
            score = ai_insights['score']
            score_color = self._get_score_color(score)
            
            elements.append(Spacer(1, 0.2*inch))
            
            score_data = [[
                'Portfolio Health Score',
                Paragraph(
                    f'<font color="{score_color}"><b>{score}/100</b></font>',
                    self.styles['Emphasis']
                )
            ]]
            
            score_table = Table(score_data, colWidths=[3*inch, 2*inch])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), ColorScheme.BACKGROUND_LIGHTER),
                ('ALIGN', (0, 0), (0, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 12),
                ('RIGHTPADDING', (0, 0), (-1, -1), 12),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('BOX', (0, 0), (-1, -1), 1, ColorScheme.BORDER)
            ]))
            
            elements.append(score_table)
        
        return elements
    
    def _create_key_metrics(self, portfolio_data: Dict, analytics: Dict) -> List:
        """Create key metrics dashboard"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Key Metrics Dashboard</b>",
            self.styles['SectionHeader']
        ))
        
        summary = portfolio_data.get('summary', {})
        risk_metrics = analytics.get('risk_metrics', {})
        
        # Create 2x3 metrics grid
        metrics_data = [
            [
                self._create_metric_cell('Total Value', f"${summary.get('total_value', 0):,.2f}"),
                self._create_metric_cell('Daily Change', f"${summary.get('total_daily_change', 0):+,.2f}")
            ],
            [
                self._create_metric_cell('Total Return', f"{summary.get('overall_return_pct', 0):+.2f}%"),
                self._create_metric_cell('Sharpe Ratio', f"{risk_metrics.get('sharpe_ratio', 0):.2f}")
            ],
            [
                self._create_metric_cell('Holdings', str(summary.get('num_holdings', 0))),
                self._create_metric_cell('Annual Income', f"${summary.get('total_annual_income', 0):,.2f}")
            ]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[2.75*inch, 2.75*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), ColorScheme.BACKGROUND_LIGHT),
            ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        elements.append(metrics_table)
        
        return elements
    
    def _create_metric_cell(self, label: str, value: str) -> List:
        """Create a formatted metric cell"""
        return [
            Paragraph(f"<font size=9 color='#{ColorScheme.TEXT_SECONDARY.hexval()}'>{label}</font>", self.styles['Normal']),
            Paragraph(f"<b><font size=14>{value}</font></b>", self.styles['Normal'])
        ]
    
    def _create_portfolio_overview(self, portfolio_data: Dict) -> List:
        """Create portfolio overview section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Portfolio Overview</b>",
            self.styles['SectionHeader']
        ))
        
        summary = portfolio_data.get('summary', {})
        holdings = portfolio_data.get('holdings', [])
        
        # Summary statistics
        stats_data = [
            ['Metric', 'Value'],
            ['Total Portfolio Value', f"${summary.get('total_value', 0):,.2f}"],
            ['Total Cost Basis', f"${summary.get('total_principal', 0):,.2f}"],
            ['Total Gain/Loss', f"${summary.get('total_gain_loss', 0):+,.2f}"],
            ['Number of Holdings', str(len(holdings))],
            ['Largest Holding', self._get_largest_holding(holdings)],
            ['Smallest Holding', self._get_smallest_holding(holdings)],
            ['Average Holding Size', f"${summary.get('total_value', 0) / max(len(holdings), 1):,.2f}"]
        ]
        
        stats_table = Table(stats_data, colWidths=[3*inch, 2.5*inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ColorScheme.PRIMARY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('TOPPADDING', (0, 0), (-1, 0), 12),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ColorScheme.BACKGROUND_LIGHTER]),
            ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))
        
        elements.append(stats_table)
        
        return elements
    
    def _create_holdings_table(self, portfolio_data: Dict) -> List:
        """Create detailed holdings table"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Portfolio Holdings Detail</b>",
            self.styles['SectionHeader']
        ))
        
        holdings = portfolio_data.get('holdings', [])
        summary = portfolio_data.get('summary', {})
        
        if not holdings:
            elements.append(Paragraph("No holdings data available.", self.styles['BodyText']))
            return elements
        
        # Sort by value
        sorted_holdings = sorted(
            holdings,
            key=lambda x: x.get('Value ($)', 0),
            reverse=True
        )
        
        # Table headers
        table_data = [[
            'Symbol',
            'Quantity',
            'Price',
            'Value',
            'Weight',
            'Gain/Loss',
            'Return %'
        ]]
        
        total_value = summary.get('total_value', 1)
        
        # Add holdings (limit to top 25)
        for holding in sorted_holdings[:25]:
            symbol = str(holding.get('Symbol', 'N/A'))[:10]
            quantity = holding.get('Quantity', 0)
            price = holding.get('Price ($)', 0)
            value = holding.get('Value ($)', 0)
            weight = (value / total_value * 100) if total_value > 0 else 0
            gain_loss = holding.get('NFS G/L ($)', 0)
            return_pct = holding.get('NFS G/L (%)', 0)
            
            # Color code gain/loss
            gl_color = ColorScheme.SUCCESS if gain_loss >= 0 else ColorScheme.DANGER
            
            table_data.append([
                symbol,
                f"{quantity:,.2f}",
                f"${price:,.2f}",
                f"${value:,.0f}",
                f"{weight:.1f}%",
                Paragraph(
                    f'<font color="#{gl_color.hexval()}">${gain_loss:+,.0f}</font>',
                    self.styles['Normal']
                ),
                Paragraph(
                    f'<font color="#{gl_color.hexval()}">{return_pct:+.1f}%</font>',
                    self.styles['Normal']
                )
            ])
        
        holdings_table = Table(
            table_data,
            colWidths=[0.9*inch, 0.9*inch, 0.9*inch, 1.1*inch, 0.7*inch, 1*inch, 0.9*inch]
        )
        holdings_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ColorScheme.SUCCESS),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ColorScheme.BACKGROUND_LIGHTER]),
            ('GRID', (0, 0), (-1, -1), 0.5, ColorScheme.BORDER_LIGHT),
            ('BOX', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        
        elements.append(holdings_table)
        
        if len(holdings) > 25:
            elements.append(Spacer(1, 0.1*inch))
            elements.append(Paragraph(
                f"<i>Showing top 25 of {len(holdings)} total holdings</i>",
                self.styles['SmallText']
            ))
        
        return elements
    
    def _create_risk_analysis(self, analytics: Dict) -> List:
        """Create risk analysis section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Risk Analysis</b>",
            self.styles['SectionHeader']
        ))
        
        risk_metrics = analytics.get('risk_metrics', {})
        
        if not risk_metrics:
            elements.append(Paragraph(
                "Risk metrics not available.",
                self.styles['BodyText']
            ))
            return elements
        
        risk_data = [['Metric', 'Value', 'Interpretation']]
        
        # Beta
        if 'beta' in risk_metrics:
            beta = risk_metrics['beta']
            interpretation = "Higher than market" if beta > 1 else "Lower than market"
            risk_data.append([
                'Beta',
                f"{beta:.2f}",
                interpretation
            ])
        
        # Sharpe Ratio
        if 'sharpe_ratio' in risk_metrics:
            sharpe = risk_metrics['sharpe_ratio']
            if sharpe > 2:
                interpretation = "Excellent risk-adjusted returns"
            elif sharpe > 1:
                interpretation = "Good risk-adjusted returns"
            elif sharpe > 0:
                interpretation = "Moderate risk-adjusted returns"
            else:
                interpretation = "Poor risk-adjusted returns"
            
            risk_data.append([
                'Sharpe Ratio',
                f"{sharpe:.2f}",
                interpretation
            ])
        
        # Volatility
        if 'portfolio_volatility' in risk_metrics:
            vol = risk_metrics['portfolio_volatility']
            risk_data.append([
                'Volatility (Annual)',
                f"{vol:.1f}%",
                "Standard deviation of returns"
            ])
        
        # Value at Risk
        if 'var_95' in risk_metrics:
            var = risk_metrics['var_95']
            risk_data.append([
                'Value at Risk (95%)',
                f"{var:.1f}%",
                "Potential worst-case loss"
            ])
        
        # Downside Deviation
        if 'downside_deviation' in risk_metrics:
            dd = risk_metrics['downside_deviation']
            risk_data.append([
                'Downside Deviation',
                f"{dd:.1f}%",
                "Volatility of negative returns"
            ])
        
        risk_table = Table(risk_data, colWidths=[2*inch, 1.25*inch, 2.25*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ColorScheme.DANGER),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('ALIGN', (2, 0), (2, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fee2e2')]),
            ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        elements.append(risk_table)
        
        return elements
    
    def _create_allocation_section(self, analytics: Dict) -> List:
        """Create allocation analysis section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Asset Allocation Analysis</b>",
            self.styles['SectionHeader']
        ))
        
        # Sector allocation
        sector_data = analytics.get('sector_allocation', {})
        
        if sector_data and isinstance(sector_data, dict):
            elements.append(Paragraph(
                "<b>Sector Allocation</b>",
                self.styles['SubsectionHeader']
            ))
            
            table_data = [['Sector', 'Allocation']]
            
            for sector, weight in sorted(
                sector_data.items(),
                key=lambda x: x[1] if isinstance(x[1], (int, float)) else 0,
                reverse=True
            ):
                if isinstance(weight, (int, float)):
                    table_data.append([str(sector), f"{weight:.1f}%"])
            
            if len(table_data) > 1:
                sector_table = Table(table_data, colWidths=[3.5*inch, 1.5*inch])
                sector_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), ColorScheme.SECONDARY),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (0, -1), 'LEFT'),
                    ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ColorScheme.AI_BACKGROUND]),
                    ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER),
                    ('LEFTPADDING', (0, 0), (-1, -1), 10),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                    ('TOPPADDING', (0, 0), (-1, -1), 8),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ]))
                
                elements.append(sector_table)
        
        return elements
    
    def _create_performance_section(self, analytics: Dict) -> List:
        """Create performance analysis section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Performance Analysis</b>",
            self.styles['SectionHeader']
        ))
        
        performance = analytics.get('performance', {})
        
        if performance:
            perf_data = [['Period', 'Return']]
            
            periods = ['1D', '1W', '1M', '3M', 'YTD', '1Y']
            for period in periods:
                if period in performance:
                    perf_data.append([period, f"{performance[period]:+.2f}%"])
            
            if len(perf_data) > 1:
                perf_table = Table(perf_data, colWidths=[2.5*inch, 2.5*inch])
                perf_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), ColorScheme.PRIMARY),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ColorScheme.BACKGROUND_LIGHTER]),
                    ('GRID', (0, 0), (-1, -1), 1, ColorScheme.BORDER)
                ]))
                
                elements.append(perf_table)
        
        return elements
    
    def _create_ai_insights_section(self, ai_insights: Dict) -> List:
        """Create AI insights section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>AI-Powered Insights</b>",
            self.styles['SectionHeader']
        ))
        
        # Risks
        if ai_insights.get('risks'):
            elements.append(Paragraph(
                "<b>Identified Risks</b>",
                self.styles['SubsectionHeader']
            ))
            
            for risk in ai_insights['risks'][:5]:  # Limit to top 5
                elements.append(Paragraph(
                    f"• {risk}",
                    self.styles['BodyText']
                ))
            
            elements.append(Spacer(1, 0.2*inch))
        
        # Opportunities
        if ai_insights.get('opportunities'):
            elements.append(Paragraph(
                "<b>Opportunities</b>",
                self.styles['SubsectionHeader']
            ))
            
            for opp in ai_insights['opportunities'][:5]:  # Limit to top 5
                elements.append(Paragraph(
                    f"• {opp}",
                    self.styles['BodyText']
                ))
        
        return elements
    
    def _create_recommendations_section(self, ai_insights: Dict) -> List:
        """Create recommendations section"""
        elements = []
        
        elements.append(Paragraph(
            "<b>Strategic Recommendations</b>",
            self.styles['SectionHeader']
        ))
        
        recommendations = ai_insights.get('recommendations', [])
        
        for i, rec in enumerate(recommendations, 1):
            elements.append(Paragraph(
                f"<b>{i}.</b> {rec}",
                self.styles['BodyText']
            ))
            elements.append(Spacer(1, 0.15*inch))
        
        return elements
    
    def _create_disclaimer(self) -> List:
        """Create disclaimer section"""
        elements = []
        
        elements.append(Spacer(1, 0.5*inch))
        
        elements.append(Paragraph(
            "<b>Important Disclaimer</b>",
            self.styles['SubsectionHeader']
        ))
        
        disclaimer_text = """
        This report is for informational purposes only and does not constitute investment advice, 
        financial advice, trading advice, or any other sort of advice. The information contained 
        herein is based on data available at the time of generation and may not reflect current 
        market conditions. Past performance is not indicative of future results. 
        <br/><br/>
        All investments carry risk, including the potential loss of principal. Before making any 
        investment decisions, you should consult with a qualified financial advisor who can assess 
        your individual circumstances and objectives.
        <br/><br/>
        <b>VisionWealth</b> and its affiliates make no representations or warranties regarding 
        the accuracy, completeness, or timeliness of the information provided in this report.
        """
        
        elements.append(Paragraph(disclaimer_text, self.styles['Disclaimer']))
        
        return elements
    
    # Helper methods
    
    def _get_largest_holding(self, holdings: List[Dict]) -> str:
        """Get largest holding by value"""
        if not holdings:
            return "N/A"
        
        try:
            largest = max(holdings, key=lambda x: x.get('Value ($)', 0))
            ticker = largest.get('Symbol', 'N/A')
            value = largest.get('Value ($)', 0)
            return f"{ticker} (${value:,.0f})"
        except:
            return "N/A"
    
    def _get_smallest_holding(self, holdings: List[Dict]) -> str:
        """Get smallest holding by value"""
        if not holdings:
            return "N/A"
        
        try:
            smallest = min(holdings, key=lambda x: x.get('Value ($)', 0))
            ticker = smallest.get('Symbol', 'N/A')
            value = smallest.get('Value ($)', 0)
            return f"{ticker} (${value:,.0f})"
        except:
            return "N/A"
    
    def _get_score_color(self, score: int) -> str:
        """Get color for portfolio score"""
        if score >= 80:
            return f"#{ColorScheme.SUCCESS.hexval()}"
        elif score >= 60:
            return f"#{ColorScheme.WARNING.hexval()}"
        else:
            return f"#{ColorScheme.DANGER.hexval()}"


# ========================================
# CONVENIENCE FUNCTIONS
# ========================================

# Global instance
_pdf_generator = None


def get_pdf_generator() -> EnhancedPDFReportGenerator:
    """Get or create PDF generator singleton"""
    global _pdf_generator
    if _pdf_generator is None:
        _pdf_generator = EnhancedPDFReportGenerator()
    return _pdf_generator


def generate_portfolio_pdf(
    portfolio_data: Dict,
    analytics_data: Dict,
    output_path: str,
    client_name: str = "Client",
    ai_insights: Optional[Dict] = None
) -> bytes:
    """
    Convenience function to generate PDF report.
    
    Args:
        portfolio_data: Portfolio data dictionary
        analytics_data: Analytics data dictionary
        output_path: Path to save PDF
        client_name: Client name for report
        ai_insights: Optional AI insights
    
    Returns:
        PDF as bytes
    """
    generator = get_pdf_generator()
    return generator.generate_report(
        portfolio_data=portfolio_data,
        analytics=analytics_data,
        ai_insights=ai_insights,
        output_path=output_path,
        client_name=client_name
    )
