"""
Report Service for VisionWealth
Handles generation of PDF reports using ReportLab with professional formatting
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, 
    Image, PageBreak, KeepTogether, Frame, PageTemplate
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from io import BytesIO
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class NumberedCanvas(canvas.Canvas):
    """Custom canvas for adding page numbers and footers"""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []
    
    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()
    
    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
    
    def draw_page_number(self, page_count):
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.grey)
        page_num = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 0.75 * inch, 0.5 * inch, page_num)
        self.drawString(0.75 * inch, 0.5 * inch, f"Generated by VisionWealth - {datetime.now().strftime('%B %d, %Y')}")


class ReportService:
    """Professional report generation service using ReportLab"""
    
    # Color palette
    PRIMARY_BLUE = colors.HexColor('#1e40af')
    SECONDARY_BLUE = colors.HexColor('#3b82f6')
    LIGHT_BLUE = colors.HexColor('#eff6ff')
    GRAY_700 = colors.HexColor('#374151')
    GRAY_100 = colors.HexColor('#f3f4f6')
    GRAY_200 = colors.HexColor('#e5e7eb')
    GREEN = colors.HexColor('#10b981')
    RED = colors.HexColor('#ef4444')
    
    def __init__(self):
        """Initialize the report service"""
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Set up custom paragraph styles"""
        self.title_style = ParagraphStyle(
            'CustomTitle', parent=self.styles['Heading1'], fontSize=28,
            textColor=self.PRIMARY_BLUE, spaceAfter=30, alignment=TA_CENTER, fontName='Helvetica-Bold'
        )
        
        self.subtitle_style = ParagraphStyle(
            'CustomSubtitle', parent=self.styles['Normal'], fontSize=14,
            textColor=self.GRAY_700, spaceAfter=20, alignment=TA_CENTER
        )
        
        self.header_style = ParagraphStyle(
            'CustomHeader', parent=self.styles['Heading2'], fontSize=18,
            textColor=self.PRIMARY_BLUE, spaceBefore=20, spaceAfter=12, fontName='Helvetica-Bold'
        )
        
        self.subheader_style = ParagraphStyle(
            'CustomSubheader', parent=self.styles['Heading3'], fontSize=14,
            textColor=self.GRAY_700, spaceBefore=15, spaceAfter=8, fontName='Helvetica-Bold'
        )
        
        self.body_style = ParagraphStyle(
            'CustomBody', parent=self.styles['Normal'], fontSize=10,
            textColor=colors.black, spaceAfter=12, alignment=TA_JUSTIFY
        )
    
    @staticmethod
    def generate_portfolio_report(
        portfolio_data: Dict[str, Any],
        user_name: str = "Client",
        include_analytics: bool = True,
        page_size: tuple = letter
    ) -> BytesIO:
        """Generate a comprehensive PDF report for the portfolio"""
        logger.info(f"Generating portfolio report for {user_name}")
        
        try:
            service = ReportService()
            buffer = BytesIO()
            
            doc = SimpleDocTemplate(
                buffer, pagesize=page_size, rightMargin=0.75 * inch, leftMargin=0.75 * inch,
                topMargin=1 * inch, bottomMargin=1 * inch,
                title=f"Portfolio Report - {user_name}", author="VisionWealth Platform"
            )
            
            elements = []
            elements.extend(service._create_cover_page(user_name))
            elements.append(PageBreak())
            elements.extend(service._create_executive_summary(portfolio_data))
            elements.extend(service._create_holdings_section(portfolio_data))
            
            if include_analytics:
                elements.extend(service._create_analytics_section(portfolio_data))
            
            elements.extend(service._create_performance_section(portfolio_data))
            elements.extend(service._create_allocation_section(portfolio_data))
            
            doc.build(elements, canvasmaker=NumberedCanvas)
            buffer.seek(0)
            logger.info("Portfolio report generated successfully")
            return buffer
            
        except Exception as e:
            logger.error(f"Error generating portfolio report: {e}", exc_info=True)
            raise
    
    def _create_cover_page(self, user_name: str) -> List:
        """Create professional cover page"""
        elements = []
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("Portfolio Analysis Report", self.title_style))
        elements.append(Spacer(1, 0.3 * inch))
        elements.append(Paragraph(f"Prepared for: <b>{user_name}</b>", self.subtitle_style))
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y')}", self.subtitle_style))
        elements.append(Spacer(1, 3 * inch))
        
        disclaimer = """<i>This report is generated by VisionWealth Platform and contains confidential 
        information. The data presented is for informational purposes only and should 
        not be construed as investment advice. Past performance does not guarantee future results.</i>"""
        elements.append(Paragraph(disclaimer, self.body_style))
        
        return elements
    
    def _create_executive_summary(self, portfolio_data: Dict[str, Any]) -> List:
        """Create executive summary section"""
        elements = []
        elements.append(Paragraph("Executive Summary", self.header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        summary = portfolio_data.get('summary', {})
        total_value = summary.get('total_value', 0)
        num_holdings = summary.get('num_holdings', 0)
        
        summary_text = f"""Your portfolio currently consists of <b>{num_holdings}</b> holdings with a 
        total market value of <b>${total_value:,.2f}</b>. This report provides a 
        comprehensive analysis of your investment positions, performance metrics, and risk characteristics."""
        
        elements.append(Paragraph(summary_text, self.body_style))
        elements.append(Spacer(1, 0.3 * inch))
        
        summary_data = [
            ["Metric", "Value"],
            ["Total Portfolio Value", self._format_currency(total_value)],
            ["Total Daily Change", self._format_currency_with_sign(summary.get('total_daily_change', 0))],
            ["Daily Return", self._format_percentage_with_sign(summary.get('daily_return_pct', 0))],
            ["Number of Holdings", str(num_holdings)],
            ["Cash Position", self._format_currency(summary.get('cash', 0))],
            ["Last Updated", datetime.now().strftime('%Y-%m-%d %H:%M')]
        ]
        
        t = Table(summary_data, colWidths=[3.5 * inch, 3 * inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.LIGHT_BLUE),
            ('TEXTCOLOR', (0, 0), (-1, 0), self.PRIMARY_BLUE),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, self.GRAY_200),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))
        
        elements.append(t)
        elements.append(Spacer(1, 0.5 * inch))
        return elements
    
    def _create_holdings_section(self, portfolio_data: Dict[str, Any]) -> List:
        """Create detailed holdings section"""
        elements = []
        elements.append(Paragraph("Portfolio Holdings", self.header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        holdings = portfolio_data.get('holdings', [])
        if not holdings:
            elements.append(Paragraph("No holdings data available.", self.body_style))
            return elements
        
        sorted_holdings = sorted(holdings, key=lambda x: x.get('Value ($)', 0), reverse=True)
        elements.append(Paragraph("Top 10 Holdings by Value", self.subheader_style))
        elements.append(Spacer(1, 0.1 * inch))
        
        holdings_data = [["Symbol", "Description", "Shares", "Price", "Value", "Allocation"]]
        
        for h in sorted_holdings[:10]:
            holdings_data.append([
                h.get('Symbol', 'N/A'),
                self._truncate_text(h.get('Description', 'N/A'), 25),
                self._format_number(h.get('Shares', 0)),
                self._format_currency(h.get('Price ($)', 0)),
                self._format_currency(h.get('Value ($)', 0)),
                f"{h.get('Assets (%)', 0):.2f}%"
            ])
        
        total_value = sum(h.get('Value ($)', 0) for h in holdings)
        holdings_data.append(["TOTAL", "", "", "", self._format_currency(total_value), "100.00%"])
        
        t = Table(holdings_data, colWidths=[0.8 * inch, 2 * inch, 0.8 * inch, 0.8 * inch, 1.2 * inch, 0.9 * inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.GRAY_100),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, self.GRAY_200),
            ('ALIGN', (2, 1), (-1, -1), 'RIGHT'),
            ('BACKGROUND', (0, -1), (-1, -1), self.LIGHT_BLUE),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('LINEABOVE', (0, -1), (-1, -1), 2, self.PRIMARY_BLUE),
        ]))
        
        elements.append(t)
        elements.append(Spacer(1, 0.5 * inch))
        return elements
    
    def _create_analytics_section(self, portfolio_data: Dict[str, Any]) -> List:
        """Create analytics section with risk metrics"""
        elements = []
        analytics = portfolio_data.get('analytics', {})
        if not analytics:
            return elements
        
        elements.append(PageBreak())
        elements.append(Paragraph("Risk Analytics", self.header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        risk_metrics = analytics.get('risk_metrics', {})
        if risk_metrics:
            risk_data = [["Metric", "Value", "Interpretation"]]
            
            volatility = risk_metrics.get('volatility', 0)
            risk_data.append(["Volatility (Annualized)", f"{volatility * 100:.2f}%", self._interpret_volatility(volatility)])
            
            sharpe = risk_metrics.get('sharpe_ratio', 0)
            risk_data.append(["Sharpe Ratio", f"{sharpe:.2f}", self._interpret_sharpe(sharpe)])
            
            beta = risk_metrics.get('beta', 0)
            if beta:
                risk_data.append(["Beta", f"{beta:.2f}", self._interpret_beta(beta)])
            
            t = Table(risk_data, colWidths=[2 * inch, 1.5 * inch, 3 * inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.LIGHT_BLUE),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, self.GRAY_200),
            ]))
            
            elements.append(t)
            elements.append(Spacer(1, 0.3 * inch))
        
        return elements
    
    def _create_performance_section(self, portfolio_data: Dict[str, Any]) -> List:
        """Create performance metrics section"""
        elements = []
        performance = portfolio_data.get('analytics', {}).get('performance', {})
        if not performance:
            return elements
        
        elements.append(Paragraph("Performance Metrics", self.header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        perf_data = [["Period", "Return", "Status"]]
        periods = {'1D': '1_day', '1W': '1_week', '1M': '1_month', '3M': '3_months', 'YTD': 'ytd', '1Y': '1_year'}
        
        for label, key in periods.items():
            value = performance.get(key, 0)
            perf_data.append([label, self._format_percentage_with_sign(value), "Gain" if value >= 0 else "Loss"])
        
        t = Table(perf_data, colWidths=[1.5 * inch, 2 * inch, 2 * inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.GRAY_100),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, self.GRAY_200),
        ]))
        
        elements.append(t)
        elements.append(Spacer(1, 0.5 * inch))
        return elements
    
    def _create_allocation_section(self, portfolio_data: Dict[str, Any]) -> List:
        """Create asset allocation section"""
        elements = []
        allocation = portfolio_data.get('analytics', {}).get('allocation', {})
        if not allocation:
            return elements
        
        elements.append(Paragraph("Asset Allocation", self.header_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        sectors = allocation.get('sectors', {})
        if sectors:
            elements.append(Paragraph("Sector Breakdown", self.subheader_style))
            elements.append(Spacer(1, 0.1 * inch))
            
            sector_data = [["Sector", "Allocation", "Value"]]
            total_value = portfolio_data.get('summary', {}).get('total_value', 0)
            
            for sector, pct in sorted(sectors.items(), key=lambda x: x[1], reverse=True):
                value = total_value * (pct / 100)
                sector_data.append([sector, f"{pct:.2f}%", self._format_currency(value)])
            
            t = Table(sector_data, colWidths=[3 * inch, 1.5 * inch, 2 * inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.LIGHT_BLUE),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, self.GRAY_200),
                ('ALIGN', (1, 1), (-1, -1), 'RIGHT'),
            ]))
            
            elements.append(t)
        
        return elements
    
    # Helper methods
    @staticmethod
    def _format_currency(value: float) -> str:
        return f"${value:,.2f}"
    
    @staticmethod
    def _format_currency_with_sign(value: float) -> str:
        sign = "+" if value >= 0 else ""
        return f"{sign}${value:,.2f}"
    
    @staticmethod
    def _format_percentage_with_sign(value: float) -> str:
        sign = "+" if value >= 0 else ""
        return f"{sign}{value:.2f}%"
    
    @staticmethod
    def _format_number(value: float) -> str:
        return f"{value:,.2f}"
    
    @staticmethod
    def _truncate_text(text: str, max_length: int) -> str:
        if len(text) <= max_length:
            return text
        return text[:max_length - 3] + "..."
    
    @staticmethod
    def _interpret_volatility(volatility: float) -> str:
        if volatility < 0.10:
            return "Low volatility"
        elif volatility < 0.20:
            return "Moderate volatility"
        elif volatility < 0.30:
            return "High volatility"
        else:
            return "Very high volatility"
    
    @staticmethod
    def _interpret_sharpe(sharpe: float) -> str:
        if sharpe < 0:
            return "Poor risk-adjusted returns"
        elif sharpe < 1:
            return "Below average"
        elif sharpe < 2:
            return "Good"
        elif sharpe < 3:
            return "Very good"
        else:
            return "Excellent"
    
    @staticmethod
    def _interpret_beta(beta: float) -> str:
        if beta < 0.8:
            return "Less volatile than market"
        elif beta < 1.2:
            return "Similar to market"
        else:
            return "More volatile than market"
