"""
Report Service for VisionWealth
Handles generation of PDF reports using ReportLab
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
from typing import Dict, Any, List
from datetime import datetime

class ReportService:
    @staticmethod
    def generate_portfolio_report(portfolio_data: Dict[str, Any], user_name: str = "Client") -> BytesIO:
        """
        Generate a PDF report for the portfolio
        Returns a BytesIO object containing the PDF
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        elements = []
        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'), # Blue-800
            spaceAfter=20
        )
        
        header_style = ParagraphStyle(
            'Header',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#374151'), # Gray-700
            spaceBefore=15,
            spaceAfter=10
        )
        
        # 1. Title Page / Header
        elements.append(Paragraph("VisionWealth Portfolio Report", title_style))
        elements.append(Paragraph(f"Prepared for: {user_name}", styles['Normal']))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
        elements.append(Spacer(1, 0.5 * inch))
        
        # 2. Executive Summary
        summary = portfolio_data.get('summary', {})
        elements.append(Paragraph("Executive Summary", header_style))
        
        summary_data = [
            ["Metric", "Value"],
            ["Total Portfolio Value", f"${summary.get('total_value', 0):,.2f}"],
            ["Total Daily Change", f"${summary.get('total_daily_change', 0):,.2f}"],
            ["Daily Return", f"{summary.get('daily_return_pct', 0):.2f}%"],
            ["Number of Holdings", str(summary.get('num_holdings', 0))]
        ]
        
        t = Table(summary_data, colWidths=[3*inch, 3*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#eff6ff')), # Blue-50
            ('TEXTCOLOR', (0, 0), (1, 0), colors.HexColor('#1e40af')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e5e7eb'))
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.5 * inch))
        
        # 3. Top Holdings
        elements.append(Paragraph("Top Holdings", header_style))
        
        holdings = portfolio_data.get('holdings', [])
        # Sort by value and take top 10
        top_holdings = sorted(holdings, key=lambda x: x.get('Value ($)', 0), reverse=True)[:10]
        
        holdings_data = [["Symbol", "Description", "Value", "Alloc %"]]
        for h in top_holdings:
            holdings_data.append([
                h.get('Symbol', ''),
                h.get('Description', '')[:30], # Truncate description
                f"${h.get('Value ($)', 0):,.2f}",
                f"{h.get('Assets (%)', 0):.2f}%"
            ])
            
        t2 = Table(holdings_data, colWidths=[1*inch, 3*inch, 1.5*inch, 1*inch])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')), # Gray-100
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('ALIGN', (2, 1), (-1, -1), 'RIGHT'), # Align numbers right
        ]))
        elements.append(t2)
        
        # 4. Footer
        elements.append(Spacer(1, 1 * inch))
        elements.append(Paragraph("Generated by VisionWealth Platform", styles['Italic']))
        
        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer
